apiVersion: v1
kind: Pod
metadata:
  name: mariana-nginx
  labels:
    app: mariana-nginx
spec:
  containers:
    - name: container-pod-nginx
      image: nginx:latest
      ports:
        - containerPort: 80

# kubectl apply -f pod-nginx.yml
# kubectl describe -f pod-nginx.yml
# kubectl delete -f pod-nginx.yml

apiVersion: v1
kind: Pod
metadata:
  name: mariana-nodejs
  labels:
    app: mariana-nodejs
spec:
  containers:
    - name: container-pod-nodejs
      image: didox/app-nodejs-validacao-cnpj
      ports:
        - containerPort: 3000
