- hosts: all
  become: true

  tasks:
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - default-jdk
        - nginx

    - name: "Copia Chave privada ssh"
      copy:
        src: "/home/ubuntu/id_rsa"
        dest: "/var/lib/jenkins/.ssh/id_rsa"
        owner: jenkins
        group: jenkins
        mode: '0400'
