# Cria recurso externo do cluster, pode ser utilizado um nginx com proxypass para um unico IP

apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-nodejs-mariana
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001 # 30000 ~ 32767
  selector:
    app: mariana-nodejs

# kubectl apply -f node-port-nginx.yml
# kubectl describe -f node-port-nginx.yml
# kubectl delete -f node-port-nginx.yml